travis:
  secure:
    BINSTAR_TOKEN: vAHT1UrTSmX3lvYEpTv+MnFtGYqg8Ist6WPajfClTlOOMiv/6sCPx09A8whRWZAhb+5mQb3xJ5zbpMpDC5K0vDPmQeKuc1CtMFJhZtf6VCMggvg86zRUzGNlCLIXO9lmWWbj6DsVXrcEN+XGyEERKPYj9hMfGBrCfi/F1isuySid+X0Cw4fDdEhMQWrpCL4CIYG1CCIadUyhf3zAm8lLhROLcDwsGwwpGVoOmcIBSeObBbUVy9aMm+GVlW70jEGI2mwpkIKLl8RzLWTjUJQ/5QeVXz1oYHoql5mxcUwX7zEIbyMsrsoG41VLsOywzhk7gfGzDfrShWd2MqWYBfvS+V2tl4g4KccBMncaq+a73tOgXh0wzKMYCy7rS6Ky6DkNyJkXpKrgjyNft+YzqSP9qhwnT6SNz96Ksh+Xs4JlhygGr+45+j/byaPKrXblmVaVyCF+LpwXTTGecXCI9jWI7dlazlt2tziO++qeg3eqE2vHYxb0pbRD3mqDnHOLTHFxxJnGq5TZtMYnvDEYelz6JRNsrpooKhBwlLv/FgZbWP4nvJ9Yt/WDVkVJGs8AnibQVdy9T+VL/RADfbacwkeeU5pB4CVwS5SKnsHtSYZkWg7SHNJl3MW1oUgxkmAJHPIV2PWg0zrhGu97uTDCjU7KhX5elZkOJ6Fzn1MNgG1gcak=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
