appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lWX+25monUOLq5dlyXV5J1fWiAW8+xwhDY950TQTvRcbrWn5KQG175AtzadvT+Jwi1USEBpIr/hNDCTJKWK/0LKovh6g6p/VAz+s+nJUh/iP1ZdMOQ5NrNEuARO2EGfgslTbvXrAES6c+erAnOYB5nKKSAc6ZkLp1brLhVwSAVQsTZQ/xY+NjKCWbHhr5ikQwNp9gdXAKl7n22T9tcz0jXxTEAJerVGORfHCGfNHWiKZ6DvrFJ4ftx79DTror+7PHW5AeFMKSS0wIzP4Hs3XpuM3yKEicszRjBbnG6xvffq5gS0F1JCKKkOL59kBqU+nOGxp7iqOitUk6XCX/79Qo+ENIbbyw1HQjjh80IkIh75aR6uRu83ytcqhGMBhhKxHNF9oKeqekPprexnhtqMysV6mZFxtBAfMRAEcbjRc5vRVW3TpR0J12yu0mOYA6AsCeAZAz6uSCNTZ+IVZxX813rb4JOY4/YeeGg15EmwEjE3sLo2hi8oVwiF0oL4TlW0ZHm/QN+38Gf8oepe+Usj2h+jzVrbqhYgeUSidQMPkxVbMvIrXNZ5+maLZIH98tThoABGJ851hrA7EdOnDvlYQm6a3SYdjYfAbdvsU6o3TnnuMG6hsDr6Px6UzY/yVxWmyXVRfJ7vK4KJCOxG+ZD5e4A54xHX9PG3JbNlQ3TZ4cBw=}
